apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scribe.fullname" . }}-backend
  labels:
    app: scribe-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scribe-backend
  template:
    metadata:
      labels:
        app: scribe-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
