apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scribe.fullname" . }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "scribe.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "scribe.name" . }}
        app.kubernetes.io/name: {{ include "scribe.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: scribe-frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: "/"
              port: {{ .Values.frontend.port }}
          livenessProbe:
            httpGet:
              path: "/"
              port: {{ .Values.frontend.port }}
