apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scribe.fullname" . }}-backend
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scribe-backend
  template:
    metadata:
      labels:
        app: scribe-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
