apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scribe.fullname" . }}-frontend
  labels:
    app: scribe-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scribe-frontend
  template:
    metadata:
      labels:
        app: scribe-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: VITE_API_URL
              value: {{ .Values.env.VITE_API_URL | quote }}
