{{- if and .Values.backend.modelSettings.enabled .Values.backend.modelSettings.create (not .Values.backend.modelSettings.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.modelSettings.pvcName }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
spec:
  accessModes:
{{- toYaml .Values.backend.modelSettings.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backend.modelSettings.storageSize }}
{{- end }}
