replicaCount: 1

frontend:
  repository: vinchar/transcriber-frontend
  tag: "0.0.6"
  pullPolicy: IfNotPresent
  port: 80

backend:
  repository: vinchar/transcriber-backend
  tag: "0.0.6"
  pullPolicy: IfNotPresent
  port: 8000

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

livenessProbe:
  path: "/"
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

# Istio VirtualService settings for PCAI
ezua:
  virtualService:
    endpoint: "scribe.${DOMAIN_NAME}"
    domain: "${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"
