replicaCount: 1

domainName: "example.com"  # <-- OVERRIDABLE

frontend:
  repository: vinchar/transcriber-frontend
  tag: "0.1.1"
  pullPolicy: IfNotPresent
  port: 80

backend:
  repository: vinchar/transcriber-backend
  tag: "0.1.0"
  pullPolicy: IfNotPresent
  port: 8000

service:
  type: ClusterIP
  port: 80

ezua:
  virtualService:
    istioGateway: "istio-system/ezaf-gateway"
